### ISSUE TITLE
Multichart - area type: why areas are summed?

### ISSUE THREAD

**Issue by tmontanaro** [nvd3/nvd3#9]
I'm trying to use the "multichart" chart and I noticed that, if more than series is set to type "area" they are shown as a sum.
You can see it in the official examples (by selecting multichart):
http://nvd3-community.github.io/nvd3/examples/site.html

Is there a way to obtain areas but without sum? Is it a bug?

**Comment by liquidpele** [comment]
That's because it's a stackedAreaChart... since they're stacked, the full height is a sum.

**Comment by liquidpele** [comment]
If you want area chart's that are not stacked and transparent, you can use the normal line chart and there is a setting to "fill in" the area for a line chart item.  Look at the "lineChart" example for how to do that.

**Comment by tmontanaro** [comment]
Ooook, thank you!
Let me say that it is not obvious :smile:
